services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn eventmng.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
